### ISSUE TITLE
Number of issues with cloudformation templates

### ISSUE THREAD

**Issue by sigit2** [Silas-cloudspace/PROJECTS-AWS-CLOUDFORMATION#1]
main.yaml

ECSTaskExecutionRole

This needs permission to pull ECR images, otherwise no tasks start. My fix:

```
Policies:
- PolicyName: "InlinePolicyECRImage"
  PolicyDocument:
    Version: "2012-10-17"
    Statement:
      - Effect: "Allow"
        Action:
          - "ecr:BatchCheckLayerAvailability"
          - "ecr:GetDownloadUrlForLayer"
          - "ecr:BatchGetImage"
          - "ecr:GetAuthorizationToken"
        Resource: "*"
```

ecs-alb.yaml

KeycloakTargetGroup

You get authentication issues logging in, if you don't enable Target Group stickiness.

My fix:
```
     TargetGroupAttributes:
        - Key: stickiness.enabled
          Value: true
        - Key: stickiness.type
          Value: lb_cookie
        - Key: stickiness.app_cookie.duration_seconds
          Value: "86400"  # 24 Hours
```

KeycloakListener

Needs more secure policy by default. My fix:
```
     SslPolicy: ELBSecurityPolicy-TLS13-1-2-2021-06

```

DefaultCapacityProviderStrategy for KeycloakCluster - "base" should be "Base" - it's case sensitive.
